### ISSUE TITLE
Embedding

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/osme#13]
OSME Webserver zeigt Controls und erzeugt lokal am Client ein XML mit einem Hashcode oder UUID als Namen. Dieses kann ich dann downloaden.

Am All-Incl Server osmeducation.org läuft eine Wordpress Instanz (/wp) und die OSMD bibliothek ist über /osmd-viewer abrufbar.
Auf /wp/upload kann man per drag'n'drop musicxmls raufladen.
Die Url zu einem raufgeladenen xml-file kann nun als Parameter beim Aufruf von /osmd-viewer angegeben werden.

**Comment by FloHin** [comment]
osme-server is done so far

POST /sheet/generate generates a file  see /sheet/generate/example/1
GET /sheet/ ... list all generated files
GET /sheet/:id returns file

**Comment by matt-uib** [comment]
https://opensheetmusiceducation.org/wp-content/uploads/osme/?embedded=1&openUrl=https://opensheetmusiceducation.org/wp-content/uploads/osme/Beethoven_AnDieFerneGeliebte.xml

**Comment by sschmidTU** [comment]
done
https://opensheetmusiceducation.org/generate-sight-reading-practice/
https://opensheetmusiceducation.org/embedding/

```html
<iframe src="https://opensheetmusiceducation.org/wp-content/uploads/viewer/?embedded=1&showHeader=0&showZoomControl=1&zoom=1.0&openUrl=https://opensheetmusiceducation.org/index.php?gf-download=2020%2F03%2Fosme_sightreading_practice_c_major_16.musicxml&form-id=1&field-id=4&hash=ed3c4a4661dd629157882d7bffc4468b4fb6b5f635017ba551459ffafb8b8259&endUrl" height="1200" width="2000">
```
https://opensheetmusiceducation.org/wp-content/uploads/viewer/?embedded=1&showHeader=0&showZoomControl=1&zoom=1.0&openUrl=https://opensheetmusiceducation.org/index.php?gf-download=2020%2F03%2Fosme_sightreading_practice_c_major_16.musicxml&form-id=1&field-id=4&hash=ed3c4a4661dd629157882d7bffc4468b4fb6b5f635017ba551459ffafb8b8259&endUrl
